// blast.jsx — BLAST simulation tool

// ─────────── Mock BLAST database ───────────
// Each query has a precomputed set of hits with realistic alignments.
const BLAST_QUERIES = {
  HBB: {
    label: 'HBB · 人類 β-球蛋白',
    desc: 'Homo sapiens hemoglobin subunit beta (60 nt)',
    type: 'nucl',
    seq: 'ATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACG',
  },
  GFP: {
    label: 'GFP · 螢光蛋白片段',
    desc: 'Aequorea victoria green fluorescent protein (60 nt)',
    type: 'nucl',
    seq: 'ATGAGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGTG',
  },
  TP53: {
    label: 'TP53 · 腫瘤抑制基因',
    desc: 'Homo sapiens tumor protein p53 (60 nt)',
    type: 'nucl',
    seq: 'ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAG',
  },
  rRNA: {
    label: '16S rRNA · 細菌鑑定',
    desc: 'Bacterial 16S ribosomal RNA V4 region (60 nt)',
    type: 'nucl',
    seq: 'GTGCCAGCMGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAG',
  },
};

// Given a query key, return an ordered list of hits.
// Each hit's alignment is generated by mutating the query at given positions.
const BLAST_HITS = {
  HBB: [
    { acc:'NM_000518.5', org:'H. sapiens',     desc:'hemoglobin subunit beta (HBB)',           bits:287, eVal:'1e-79',  ident:60, cov:60, color:'#0E9384', muts:[] },
    { acc:'XM_001157637', org:'P. troglodytes', desc:'hemoglobin subunit beta (HBB)',           bits:282, eVal:'2e-78',  ident:59, cov:60, color:'#0E9384', muts:[42] },
    { acc:'XM_004052456', org:'G. gorilla',     desc:'hemoglobin subunit beta (HBB)',           bits:277, eVal:'8e-77',  ident:59, cov:60, color:'#0E9384', muts:[8, 51] },
    { acc:'NM_001284684', org:'M. mulatta',     desc:'hemoglobin subunit beta (HBB)',           bits:261, eVal:'4e-72',  ident:57, cov:60, color:'#EAA532', muts:[15, 28, 42] },
    { acc:'NM_008220.5',  org:'M. musculus',    desc:'hemoglobin, beta adult major chain',      bits:220, eVal:'3e-58',  ident:51, cov:57, color:'#EAA532', muts:[6,18,21,33,39,45,48,54,57], gaps:[60] },
    { acc:'NM_001003839', org:'D. rerio',       desc:'hemoglobin beta embryonic-1',             bits:175, eVal:'5e-44',  ident:43, cov:53, color:'#D9594C', muts:[3,9,15,21,27,30,36,39,45,51,54,57], gaps:[58,59] },
    { acc:'NM_000517.4',  org:'H. sapiens',     desc:'hemoglobin subunit alpha (HBA) — paralog', bits:89,  eVal:'2e-18',  ident:27, cov:47, color:'#9C77C7', muts:[3,6,9,12,18,24,27,30,33,36,39,42,48,51,54], gaps:[55,56,57,58,59] },
  ],
  GFP: [
    { acc:'M62653.1',     org:'A. victoria',    desc:'green fluorescent protein',               bits:287, eVal:'2e-79',  ident:60, cov:60, color:'#0E9384', muts:[] },
    { acc:'U55763.1',     org:'A. victoria',    desc:'GFP variant (S65T) — eGFP',               bits:281, eVal:'8e-78',  ident:59, cov:60, color:'#0E9384', muts:[27] },
    { acc:'AY678264.1',   org:'A. victoria',    desc:'yellow fluorescent protein (YFP)',        bits:259, eVal:'2e-71',  ident:57, cov:60, color:'#EAA532', muts:[12,27,45] },
    { acc:'AY678265.1',   org:'D. striata',     desc:'cyan fluorescent protein (CFP)',          bits:248, eVal:'9e-68',  ident:56, cov:60, color:'#EAA532', muts:[6,15,27,42] },
    { acc:'AF506027.1',   org:'D. striata',     desc:'DsRed-Express red fluorescent protein',   bits:131, eVal:'4e-30',  ident:36, cov:52, color:'#D9594C', muts:[3,9,12,18,21,24,30,33,36,42,48,51,57], gaps:[58,59] },
  ],
  TP53: [
    { acc:'NM_000546.6',  org:'H. sapiens',     desc:'tumor protein p53 (TP53)',                bits:287, eVal:'1e-79',  ident:60, cov:60, color:'#0E9384', muts:[] },
    { acc:'NM_011640.4',  org:'M. musculus',    desc:'transformation related protein 53 (Trp53)', bits:219, eVal:'5e-58', ident:51, cov:58, color:'#EAA532', muts:[9,21,27,33,42,48,54], gaps:[59] },
    { acc:'NM_003722.5',  org:'H. sapiens',     desc:'tumor protein p63 (TP63) — paralog',      bits:142, eVal:'2e-33',  ident:39, cov:55, color:'#9C77C7', muts:[3,9,15,18,24,30,36,42,45,51,54,57], gaps:[58,59] },
    { acc:'NM_005427.4',  org:'H. sapiens',     desc:'tumor protein p73 (TP73) — paralog',      bits:128, eVal:'7e-29',  ident:37, cov:53, color:'#9C77C7', muts:[6,9,12,18,21,27,30,33,39,42,48,54], gaps:[55,56,57] },
  ],
  rRNA: [
    { acc:'AY726554',     org:'E. coli K-12',         desc:'16S ribosomal RNA',                  bits:111, eVal:'2e-23',  ident:60, cov:60, color:'#0E9384', muts:[] },
    { acc:'CP019945',     org:'S. enterica',          desc:'16S ribosomal RNA',                  bits:108, eVal:'1e-22',  ident:59, cov:60, color:'#0E9384', muts:[24] },
    { acc:'AE006468',     org:'K. pneumoniae',        desc:'16S ribosomal RNA',                  bits:104, eVal:'2e-21',  ident:58, cov:60, color:'#EAA532', muts:[15,42] },
    { acc:'NR_074549',    org:'B. subtilis',          desc:'16S ribosomal RNA',                  bits:96,  eVal:'4e-19',  ident:55, cov:60, color:'#EAA532', muts:[9,18,27,33,48] },
    { acc:'NR_113382',    org:'L. acidophilus',       desc:'16S ribosomal RNA',                  bits:89,  eVal:'8e-17',  ident:53, cov:58, color:'#D9594C', muts:[6,12,21,30,36,45,51], gaps:[59] },
    { acc:'NR_117134',    org:'M. tuberculosis',      desc:'16S ribosomal RNA',                  bits:82,  eVal:'4e-15',  ident:51, cov:58, color:'#D9594C', muts:[3,9,18,24,30,39,45,51,57], gaps:[58,59] },
  ],
};

// Make subject sequence from query + mut list (mismatches) + gap positions (deletions in subject)
function makeSubject(query, muts=[], gaps=[]){
  const mset = new Set(muts), gset = new Set(gaps);
  const alt = { A:'T', T:'A', G:'C', C:'G', M:'A' };
  let out = '';
  for(let i=0;i<query.length;i++){
    if(gset.has(i)) out += '-';
    else if(mset.has(i)) out += (alt[query[i]] || 'N');
    else out += query[i];
  }
  return out;
}

// ─────────── BlastTool ───────────
function BlastTool({ dark=false }){
  const [queryKey, setQueryKey] = React.useState('HBB');
  const q = BLAST_QUERIES[queryKey];
  const hits = BLAST_HITS[queryKey];

  const [phase, setPhase] = React.useState('idle'); // idle | scan | done
  const [scanProg, setScanProg] = React.useState(0);
  const [visibleHits, setVisibleHits] = React.useState(0);
  const [expanded, setExpanded] = React.useState(0); // index of expanded hit

  // run the animation
  const run = ()=>{
    setPhase('scan');
    setScanProg(0);
    setVisibleHits(0);
    setExpanded(0);
  };

  React.useEffect(()=>{
    if(phase!=='scan') return;
    if(scanProg>=100){
      setPhase('done');
      return;
    }
    const t = setTimeout(()=>setScanProg(p=>Math.min(100, p+4)), 50);
    return ()=>clearTimeout(t);
  }, [phase, scanProg]);

  React.useEffect(()=>{
    if(phase!=='done') return;
    if(visibleHits>=hits.length) return;
    const t = setTimeout(()=>setVisibleHits(v=>v+1), 90);
    return ()=>clearTimeout(t);
  }, [phase, visibleHits, hits.length]);

  // reset when query changes
  React.useEffect(()=>{
    setPhase('idle'); setScanProg(0); setVisibleHits(0); setExpanded(0);
  }, [queryKey]);

  const fg = dark?'#F0EEE5':'#0F1614';
  const muted = dark?'#9E9C90':'#707974';
  const surf = dark?'#1E211D':'#fff';
  const line = dark?'#2A2D29':'#E5E2D9';

  return (
    <div style={{ display:'flex', flexDirection:'column', gap:14 }}>
      {/* Query selector */}
      <div style={{ background:surf, borderRadius:18, padding:14, border:`1px solid ${line}` }}>
        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:10 }}>
          <div style={{ fontFamily:'Space Grotesk', fontWeight:600, fontSize:14, color:fg }}>Query</div>
          <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:10, color:muted, letterSpacing:.6 }}>
            nucleotide · 60 nt
          </div>
        </div>

        {/* preset chips */}
        <div style={{ display:'flex', gap:6, flexWrap:'wrap', marginBottom:10 }}>
          {Object.keys(BLAST_QUERIES).map(k=>{
            const on = k===queryKey;
            return (
              <button key={k} onClick={()=>setQueryKey(k)} style={{
                padding:'6px 10px', borderRadius:99,
                border:`1px solid ${on?'var(--accent)':line}`,
                background: on?'var(--accent-soft)':dark?'#14160E':'#F6F4EC',
                color: on?'var(--accent-ink)':fg,
                fontSize:11, fontWeight:600, fontFamily:'Manrope, Noto Sans TC',
                cursor:'pointer',
              }}>{BLAST_QUERIES[k].label}</button>
            );
          })}
        </div>

        {/* seq display */}
        <div style={{
          background: dark?'#14160E':'#F6F4EC', borderRadius:10,
          padding:'10px 12px', border:`1px dashed ${line}`,
        }}>
          <div style={{
            fontFamily:"'JetBrains Mono',monospace", fontSize:11.5, color:fg,
            letterSpacing:.8, lineHeight:1.5, wordBreak:'break-all',
          }}>
            {q.seq.split('').map((b,i)=>(
              <span key={i} style={{ color: BASE_COLORS[b] || fg }}>{b}</span>
            ))}
          </div>
          <div style={{ fontSize:10, color:muted, marginTop:6, fontFamily:'Noto Sans TC' }}>{q.desc}</div>
        </div>

        <button onClick={run}
          disabled={phase==='scan'}
          style={{
            width:'100%', marginTop:12, padding:'11px 14px', borderRadius:12, border:'none',
            background: phase==='scan'?'#9E9C90':'var(--accent)', color:'#fff',
            fontWeight:600, fontSize:14, fontFamily:'Manrope, system-ui',
            cursor: phase==='scan'?'default':'pointer',
            display:'flex', alignItems:'center', justifyContent:'center', gap:8,
          }}>
          <svg width="14" height="14" viewBox="0 0 22 22" fill="none">
            <circle cx="9" cy="9" r="6" stroke="#fff" strokeWidth="2"/>
            <path d="M14 14l5 5" stroke="#fff" strokeWidth="2" strokeLinecap="round"/>
          </svg>
          {phase==='idle' && '執行 BLAST 搜尋'}
          {phase==='scan' && '掃描資料庫中⋯'}
          {phase==='done' && '重新搜尋'}
        </button>
      </div>

      {/* Scanning animation */}
      {phase==='scan' && (
        <ScanAnimation prog={scanProg} dark={dark}/>
      )}

      {/* Results */}
      {phase==='done' && (
        <div>
          <div style={{
            display:'flex', justifyContent:'space-between', alignItems:'center',
            padding:'0 4px 10px',
            fontFamily:"'JetBrains Mono',monospace", fontSize:11, color:muted, letterSpacing:.5,
          }}>
            <span>BLAST RESULTS</span>
            <span><b style={{ color:fg }}>{hits.length}</b> hits · sorted by E-value</span>
          </div>

          {/* color legend */}
          <div style={{
            background:surf, borderRadius:14, padding:'10px 12px',
            border:`1px solid ${line}`, marginBottom:10,
            display:'flex', alignItems:'center', gap:10,
          }}>
            <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:10, color:muted, letterSpacing:.6 }}>BITS</div>
            <div style={{ flex:1, display:'flex', height:8, borderRadius:99, overflow:'hidden' }}>
              <div style={{ flex:1, background:'#9C77C7' }}/>
              <div style={{ flex:1, background:'#D9594C' }}/>
              <div style={{ flex:1, background:'#EAA532' }}/>
              <div style={{ flex:1, background:'#0E9384' }}/>
            </div>
            <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:10, color:muted }}>&lt;50 — 50–80 — 80–200 — &gt;200</div>
          </div>

          {hits.slice(0, visibleHits).map((h, i)=>(
            <BlastHitCard key={h.acc}
              hit={h} query={q.seq}
              isTop={i===0}
              expanded={expanded===i}
              onToggle={()=>setExpanded(expanded===i?-1:i)}
              dark={dark}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function ScanAnimation({ prog, dark }){
  const fg = dark?'#F0EEE5':'#0F1614';
  const muted = dark?'#9E9C90':'#707974';
  const surf = dark?'#1E211D':'#fff';
  const line = dark?'#2A2D29':'#E5E2D9';

  // simulated candidate sequences flying past
  const candidates = React.useMemo(()=>{
    const arr=[];
    for(let i=0;i<22;i++){
      const acc = ['NM_','XM_','NR_','XR_','EU','AY','KX'][i%7] + String(Math.floor(Math.random()*999999)).padStart(6,'0');
      const bits = Math.round(Math.random()*250 + 30);
      arr.push({ acc, bits });
    }
    return arr;
  }, []);

  const idxShown = Math.min(candidates.length, Math.floor(prog/100*candidates.length));

  return (
    <div style={{
      background:surf, borderRadius:18, padding:16, border:`1px solid ${line}`,
    }}>
      <div style={{
        display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:10,
        fontFamily:"'JetBrains Mono',monospace", fontSize:11, color:muted, letterSpacing:.5,
      }}>
        <span>SCANNING DATABASE</span>
        <span><b style={{ color:fg }}>{prog}%</b></span>
      </div>
      <ProgressBar pct={prog/100} color="var(--accent)" track={dark?'rgba(255,255,255,.08)':'rgba(0,0,0,.06)'} height={6}/>

      <div style={{
        marginTop:14, height:170, overflow:'hidden', position:'relative',
        background: dark?'#14160E':'#F6F4EC', borderRadius:10,
        border:`1px dashed ${line}`,
      }}>
        {/* scrolling candidates */}
        <div style={{
          position:'absolute', inset:'10px 12px',
          fontFamily:"'JetBrains Mono',monospace", fontSize:11,
          color:muted, lineHeight:1.6,
        }}>
          {candidates.slice(0, idxShown).map((c,i)=>{
            const opacity = Math.max(0.15, 1 - (idxShown - i - 1) * 0.08);
            const isCurrent = i===idxShown-1;
            return (
              <div key={i} style={{ display:'flex', justifyContent:'space-between', opacity, color: isCurrent ? fg : muted }}>
                <span>{isCurrent && '▸ '}{c.acc}</span>
                <span style={{ color: c.bits>200?'#0E9384':c.bits>80?'#EAA532':'#9C77C7' }}>bits {c.bits}</span>
              </div>
            );
          })}
        </div>
        {/* gradient fade */}
        <div style={{
          position:'absolute', inset:0, pointerEvents:'none',
          background: `linear-gradient(180deg, ${dark?'#14160E':'#F6F4EC'} 0%, transparent 25%, transparent 75%, ${dark?'#14160E':'#F6F4EC'} 100%)`,
        }}/>
      </div>

      <div style={{
        marginTop:10, fontSize:11, color:muted, fontFamily:'Noto Sans TC',
      }}>
        對齊 query 與資料庫中每一筆 subject，計算 score、E-value 並排序中⋯
      </div>
    </div>
  );
}

function BlastHitCard({ hit, query, isTop, expanded, onToggle, dark }){
  const fg = dark?'#F0EEE5':'#0F1614';
  const muted = dark?'#9E9C90':'#707974';
  const surf = dark?'#1E211D':'#fff';
  const line = dark?'#2A2D29':'#E5E2D9';

  const subject = makeSubject(query, hit.muts, hit.gaps);

  // bits bar scale: 0-300 normalized
  const bitsPct = Math.min(1, hit.bits/300);

  return (
    <div style={{
      background:surf, borderRadius:14, marginBottom:8,
      border:`1px solid ${isTop?'var(--accent)':line}`,
      overflow:'hidden',
    }}>
      <div onClick={onToggle} style={{
        padding:'12px 14px', cursor:'pointer',
        display:'grid', gridTemplateColumns:'1fr auto', gap:10,
      }}>
        <div style={{ minWidth:0 }}>
          <div style={{ display:'flex', alignItems:'center', gap:6, marginBottom:2 }}>
            <span style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:12, fontWeight:700, color:fg }}>
              {hit.acc}
            </span>
            {isTop && <span style={{
              fontSize:9, padding:'1px 5px', borderRadius:3, fontFamily:"'JetBrains Mono',monospace",
              background:'var(--accent-soft)', color:'var(--accent-ink)', letterSpacing:.4, fontWeight:700,
            }}>BEST</span>}
          </div>
          <div style={{ fontSize:12, color:fg, fontFamily:'Manrope, Noto Sans TC', lineHeight:1.35 }}>
            <i style={{ color:muted }}>{hit.org}</i> · {hit.desc}
          </div>
        </div>
        <div style={{ textAlign:'right' }}>
          <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:13, fontWeight:700, color:fg }}>
            {hit.bits}<span style={{ fontSize:10, color:muted, fontWeight:500 }}> bits</span>
          </div>
          <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:11, color:muted }}>
            E = {hit.eVal}
          </div>
        </div>

        <div style={{ gridColumn:'1/3', marginTop:8 }}>
          <div style={{ display:'flex', gap:6, alignItems:'center', marginBottom:4 }}>
            <div style={{ flex:1, height:5, background:dark?'rgba(255,255,255,.06)':'rgba(0,0,0,.05)', borderRadius:99, overflow:'hidden' }}>
              <div style={{ width:`${bitsPct*100}%`, height:'100%', background:hit.color, borderRadius:99 }}/>
            </div>
            <div style={{ fontFamily:"'JetBrains Mono',monospace", fontSize:10, color:muted }}>{Math.round(bitsPct*100)}</div>
          </div>
          <div style={{
            display:'flex', gap:14, fontSize:10.5, color:muted,
            fontFamily:"'JetBrains Mono',monospace", letterSpacing:.3,
          }}>
            <span>IDENT <b style={{ color:fg }}>{Math.round(hit.ident/60*100)}%</b></span>
            <span>COV <b style={{ color:fg }}>{Math.round(hit.cov/60*100)}%</b></span>
            <span style={{ marginLeft:'auto', color:muted }}>{expanded?'▾':'▸'} 對齊</span>
          </div>
        </div>
      </div>

      {expanded && (
        <BlastAlignment query={query} subject={subject} hit={hit} dark={dark}/>
      )}
    </div>
  );
}

function BlastAlignment({ query, subject, hit, dark }){
  const fg = dark?'#F0EEE5':'#0F1614';
  const muted = dark?'#9E9C90':'#707974';
  const line = dark?'#2A2D29':'#E5E2D9';
  const bg = dark?'#14160E':'#F6F4EC';

  // chunk into 30-char rows for readability
  const ROW = 30;
  const rows = [];
  for(let i=0;i<query.length;i+=ROW){
    rows.push({
      q: query.slice(i, i+ROW),
      s: subject.slice(i, i+ROW),
      start: i+1,
    });
  }

  return (
    <div style={{
      padding:'12px 14px 14px', background:bg,
      borderTop:`1px dashed ${line}`,
    }}>
      {rows.map((r, ri)=>{
        const matchLine = r.q.split('').map((b,i)=>{
          const sb = r.s[i];
          if(sb==='-' || b==='-') return ' ';
          return b===sb ? '|' : ' ';
        }).join('');
        return (
          <div key={ri} style={{
            fontFamily:"'JetBrains Mono',monospace", fontSize:11.5,
            lineHeight:1.5, marginBottom: ri<rows.length-1?8:0,
          }}>
            <div style={{ display:'flex', gap:8 }}>
              <span style={{ color:muted, width:32, textAlign:'right' }}>Q {String(r.start).padStart(2,' ')}</span>
              <span>
                {r.q.split('').map((b,i)=>(
                  <span key={i} style={{ color: r.s[i]===b ? fg : '#D9594C', fontWeight: r.s[i]===b ? 500 : 700 }}>{b}</span>
                ))}
              </span>
            </div>
            <div style={{ display:'flex', gap:8 }}>
              <span style={{ width:32 }}/>
              <span style={{ color:'var(--accent)', letterSpacing:.5 }}>{matchLine}</span>
            </div>
            <div style={{ display:'flex', gap:8 }}>
              <span style={{ color:muted, width:32, textAlign:'right' }}>S {String(r.start).padStart(2,' ')}</span>
              <span>
                {r.s.split('').map((b,i)=>(
                  <span key={i} style={{
                    color: b==='-' ? muted : r.q[i]===b ? fg : '#D9594C',
                    fontWeight: r.q[i]===b ? 500 : 700,
                  }}>{b}</span>
                ))}
              </span>
            </div>
          </div>
        );
      })}

      {/* footer stats */}
      <div style={{
        display:'flex', justifyContent:'space-between', marginTop:10, paddingTop:10,
        borderTop:`1px dashed ${line}`,
        fontFamily:"'JetBrains Mono',monospace", fontSize:10.5, color:muted, letterSpacing:.3,
      }}>
        <span>Identities <b style={{ color:fg }}>{hit.ident}/60 ({Math.round(hit.ident/60*100)}%)</b></span>
        <span>Gaps <b style={{ color:fg }}>{(hit.gaps?.length||0)}/60</b></span>
      </div>
    </div>
  );
}

Object.assign(window, { BlastTool, BLAST_QUERIES, BLAST_HITS });
