// flashcards.jsx — expanded flashcards with detail + chapter link

// Each card:
// { q, zh, a (short answer), detail (deeper explanation),
//   tag (broad category), course (course id), unit (unit index, 0-based) }

const FLASHCARDS_FULL = [
  // ── 分子生物 / DNA ──
  { q:'central dogma', zh:'中心法則', tag:'分子生物', course:'dna', unit:0,
    a:'DNA → RNA → 蛋白質的標準資訊流向。',
    detail:'Crick 1958 年提出，描述遺傳資訊在細胞內的標準流向。例外：反轉錄病毒 (HIV) 能逆轉成 RNA → DNA；prion 則完全跳過此流程。' },
  { q:'nucleotide', zh:'核苷酸', tag:'分子生物', course:'dna', unit:0,
    a:'DNA / RNA 的最小單位：磷酸 + 糖 + 鹼基。',
    detail:'DNA 的糖是「去氧核糖」，RNA 是「核糖」。四種鹼基：A、T (DNA) / U (RNA)、G、C。多個核苷酸用磷酸二酯鍵連成鏈。' },
  { q:'antiparallel', zh:'反平行', tag:'分子生物', course:'dna', unit:0,
    a:'雙股 DNA 的兩條鏈方向相反。',
    detail:'一條走 5\'→3\'、另一條走 3\'→5\'。這個方向性影響所有讀寫動作，包括聚合酶只能往 5\'→3\' 合成。' },
  { q:'GC content', zh:'GC 含量', tag:'分子生物', course:'dna', unit:5,
    a:'DNA 中 G + C 的比例。',
    detail:'GC 鍵有 3 個氫鍵、AT 只有 2 個，所以 GC 高 → Tm 高 → 結構更穩。人類 ≈ 41%、結核菌 ≈ 65%、瘧原蟲 ≈ 19%。' },
  { q:'melting temperature (Tm)', zh:'熔解溫度', tag:'分子生物', course:'dna', unit:5,
    a:'雙股分開所需的溫度。',
    detail:'短引子 thumb rule：Tm ≈ 4×(G+C) + 2×(A+T)。PCR 引子設計目標通常落在 55-65°C 之間。' },
  { q:'codon', zh:'密碼子', tag:'分子生物', course:'dna', unit:2,
    a:'mRNA 上三個連續核苷酸，編碼一個胺基酸。',
    detail:'共 64 種密碼子編碼 20 種胺基酸 → 簡併性。AUG 為起始碼（同時編 Met）；UAA / UAG / UGA 為終止碼。' },
  { q:'start codon', zh:'起始密碼子', tag:'分子生物', course:'dna', unit:2,
    a:'AUG，標記轉譯起點，同時編 Methionine。',
    detail:'真核生物的 ribosome 找到 5\' cap 後沿 mRNA 掃描，遇到第一個 AUG (Kozak context) 就開始合成蛋白質。' },
  { q:'stop codon', zh:'終止密碼子', tag:'分子生物', course:'dna', unit:2,
    a:'UAA、UAG、UGA — 不編胺基酸，標記終止。',
    detail:'被釋放因子 (release factor) 辨識，引發 ribosome 釋放完成的多肽。nonsense mutation 就是把一般密碼子變成終止碼。' },
  { q:'reading frame', zh:'閱讀框', tag:'分子生物', course:'dna', unit:6,
    a:'三個鹼基一組讀的方式。',
    detail:'一條序列有 3 個正向 + 3 個反向 = 6 個閱讀框。找 ORF 時必須全部掃過一遍。' },
  { q:'ORF', zh:'開放閱讀框', tag:'分子生物', course:'dna', unit:6,
    a:'從起始碼到終止碼間的潛在編碼區段。',
    detail:'Open Reading Frame。註解基因組時，先掃 ORF 找候選 CDS，再用同源比對與表現證據確認。' },
  { q:'reverse complement', zh:'反向互補', tag:'分子生物', course:'dna', unit:6,
    a:'先互補（A↔T、G↔C）再反轉字串。',
    detail:'5\'-ATGCGT-3\' → 互補 TACGCA → 反轉 ACGCAT，因此反向互補是 5\'-ACGCAT-3\'。順序不可顛倒。' },
  { q:'mutation', zh:'突變', tag:'分子生物', course:'dna', unit:4,
    a:'DNA 序列的改變。',
    detail:'三大類：替換 (substitution)、插入 (insertion)、刪除 (deletion)。indel 非 3n 倍數會造成 frameshift，通常後果嚴重。' },
  { q:'silent mutation', zh:'沉默突變', tag:'分子生物', course:'dna', unit:4,
    a:'改了 DNA 但不改胺基酸的突變。',
    detail:'常發生在密碼子第三位（簡併性）。即使「沉默」，仍可能影響 codon usage、轉譯速率、mRNA 二級結構。' },
  { q:'missense mutation', zh:'錯義突變', tag:'分子生物', course:'dna', unit:4,
    a:'造成胺基酸改變的點突變。',
    detail:'保守性錯義（換成性質相近的胺基酸）影響通常小；非保守性錯義可能破壞結構或活性。例：HBB 第 6 位 Glu→Val 造成鐮刀型貧血。' },
  { q:'nonsense mutation', zh:'無義突變', tag:'分子生物', course:'dna', unit:4,
    a:'把正常密碼子變成終止碼。',
    detail:'蛋白被截短，通常完全失去功能；常觸發 nonsense-mediated decay (NMD) 把 mRNA 直接降解掉。' },
  { q:'frameshift', zh:'移碼突變', tag:'分子生物', course:'dna', unit:4,
    a:'非 3n 的 indel 造成閱讀框錯位。',
    detail:'從插入/刪除點以後，所有密碼子都被錯讀，幾乎必然產生功能異常的蛋白。比點突變嚴重得多。' },
  { q:'transcription', zh:'轉錄', tag:'分子生物', course:'dna', unit:1,
    a:'DNA → RNA 的合成過程。',
    detail:'RNA polymerase 沿模板鏈 3\'→5\' 滑行，合成 5\'→3\' 的 RNA。真核生物的 pre-mRNA 還會經過加帽、加尾、剪接後才成熟。' },
  { q:'translation', zh:'轉譯', tag:'分子生物', course:'dna', unit:2,
    a:'mRNA → 蛋白質的合成過程。',
    detail:'ribosome 沿 mRNA 移動，每三個鹼基讀一次。tRNA 透過反密碼子辨識密碼子並送入對應胺基酸，逐個用肽鍵串成多肽。' },
  { q:'splicing', zh:'剪接', tag:'分子生物', course:'dna', unit:1,
    a:'切除 intron、留下 exon 的 RNA 加工。',
    detail:'由 spliceosome 執行。「選擇性剪接 (alternative splicing)」讓同一基因能做多種蛋白，是真核生物提升基因多樣性的重要方式。' },
  { q:'intron / exon', zh:'內含子 / 外顯子', tag:'分子生物', course:'dna', unit:1,
    a:'Intron 被剪掉、Exon 保留進成熟 mRNA。',
    detail:'人類基因平均含 7-8 個 exon、被遠多的 intron 隔開。Exon 長度約 100-200 bp，intron 平均 5000 bp 以上。' },
  { q:'promoter', zh:'啟動子', tag:'分子生物', course:'dna', unit:1,
    a:'基因上游、招募 RNA 聚合酶的 DNA 區段。',
    detail:'真核細胞核心啟動子常含 TATA box（-25 bp）與 transcription start site (TSS)。增強子 (enhancer) 則可離 TSS 很遠仍能調控。' },
  { q:'5\' cap', zh:'5\' 端帽子', tag:'分子生物', course:'dna', unit:1,
    a:'mRNA 5\' 端加上的修飾結構 (m7G)。',
    detail:'保護 mRNA 不被 5\'→3\' 外切酶降解，並作為核糖體掃描的辨識點。沒有 cap 的 mRNA 多被視為異常並降解。' },
  { q:'poly-A tail', zh:'PolyA 尾巴', tag:'分子生物', course:'dna', unit:1,
    a:'mRNA 3\' 端的 A 重複序列。',
    detail:'長度約 200 nt。穩定 mRNA、輔助輸出至細胞質、促進轉譯起始。「PolyA selection」是 RNA-seq 富集 mRNA 的常見策略。' },

  // ── 序列比對 ──
  { q:'dot plot', zh:'點陣圖', tag:'序列比對', course:'aln', unit:0,
    a:'兩條序列同位置相同字母 → 點 → 對角線浮現。',
    detail:'最直覺的兩兩比對視覺。重複序列出現平行短線；倒置 (inversion) 出現反斜線；常用窗口閾值（如 5 中 4 同）過濾雜訊。' },
  { q:'dynamic programming', zh:'動態規劃', tag:'序列比對', course:'aln', unit:1,
    a:'用矩陣逐格累積最佳分數的演算法策略。',
    detail:'把「最佳對齊」拆成「對角/上/左」三選一的局部決策。NW、SW、最短路徑、編輯距離都用同一個 DP 模板。' },
  { q:'Needleman-Wunsch', zh:'全域比對', tag:'序列比對', course:'aln', unit:2,
    a:'DP 全域比對：強制端到端對齊。',
    detail:'NW 1970。M[i][j] = max(對角 + match, 上 + gap, 左 + gap)。從右下角回溯。適合「整體相關 + 長度相近」的序列。' },
  { q:'Smith-Waterman', zh:'局部比對', tag:'序列比對', course:'aln', unit:3,
    a:'DP 局部比對：找最相似的子片段。',
    detail:'SW 1981。在 NW 基礎上加兩條規則：負分歸 0、從最大值回溯。適合找 motif、domain、或長序列中的短探針。' },
  { q:'BLAST', zh:'BLAST', tag:'序列比對', course:'aln', unit:4,
    a:'啟發式快速序列比對工具。',
    detail:'1990 Altschul et al.。核心策略 seed-and-extend：先用 hash table 找完全相符的短 k-mer，再向兩側延伸做局部比對。比完整 SW 快百倍。' },
  { q:'E-value', zh:'期望值', tag:'序列比對', course:'aln', unit:4,
    a:'隨機資料庫中得到此分數或更高的次數期望。',
    detail:'越小越顯著。一般以 E < 1e-5 視為同源 hit；E < 1e-50 通常是同一蛋白。E 與資料庫大小成正比 — 換大資料庫 E 會變大。' },
  { q:'bit score', zh:'bit 分數', tag:'序列比對', course:'aln', unit:4,
    a:'BLAST 結果的標準化分數，與資料庫大小無關。',
    detail:'比 raw score 更通用 — 跨不同資料庫比對時 bit 分數可直接比較。經驗：> 200 通常極顯著。' },
  { q:'BLOSUM62', zh:'BLOSUM62 計分矩陣', tag:'序列比對', course:'aln', unit:4,
    a:'蛋白質 BLAST 的預設替換計分矩陣。',
    detail:'從序列同源性 ≥ 62% 的家族中統計各胺基酸替換頻率得來。BLOSUM 數字越大代表訓練序列越像，適合短而相近的比對。' },
  { q:'PAM matrix', zh:'PAM 計分矩陣', tag:'序列比對', course:'aln', unit:4,
    a:'另一種蛋白質替換計分矩陣家族。',
    detail:'Dayhoff 1978 從手工對齊估替換機率。PAM 數字越大代表演化距離越遠。BLOSUM62 在現代多數情境中已取代 PAM250 成為預設。' },
  { q:'MSA', zh:'多序列比對', tag:'序列比對', course:'aln', unit:5,
    a:'同時把多條序列對齊到同一個座標系。',
    detail:'實務上用 progressive alignment：先建 guide tree、從最近的兩條開始合併。代表工具：Clustal Omega、MAFFT、MUSCLE。' },
  { q:'guide tree', zh:'導引樹', tag:'序列比對', course:'aln', unit:5,
    a:'progressive MSA 中決定合併順序的初步樹。',
    detail:'通常用 NJ 從距離矩陣建出；序列越像越早合併。導引樹品質會直接影響最終 MSA 的品質。' },
  { q:'HMM profile', zh:'HMM 輪廓模型', tag:'序列比對', course:'aln', unit:5,
    a:'用 HMM 描述一個序列家族的統計輪廓。',
    detail:'每個 column 有保守度分布、insertion/deletion 機率。PSI-BLAST、HMMER、Pfam 都基於此。比單一序列 query 更敏感。' },
  { q:'word size', zh:'word size', tag:'序列比對', course:'aln', unit:4,
    a:'BLAST seed 階段使用的 k-mer 長度。',
    detail:'blastn 預設 11、blastp 預設 3。word size 越大 → 越快但越漏遠源同源；越小越敏感但越慢。短 query 應降低 word size。' },

  // ── 蛋白質結構 ──
  { q:'amino acid', zh:'胺基酸', tag:'結構', course:'protein', unit:0,
    a:'蛋白質的基本單位，20 種標準胺基酸。',
    detail:'結構：中心 Cα 接 NH2、COOH、H、R 側鏈。R 群決定性質：疏水 / 極性 / 正電 / 負電。Cys 能形成雙硫鍵，Pro 會打彎。' },
  { q:'α-helix', zh:'α 螺旋', tag:'結構', course:'protein', unit:1,
    a:'右手螺旋形的二級結構，每圈 3.6 殘基。',
    detail:'由「i 與 i+4」骨架氫鍵穩定。helix 兩側通常具有兩性 (amphipathic)：一側疏水、另一側親水，常用於跨膜或穿越界面。' },
  { q:'β-sheet', zh:'β 摺片', tag:'結構', course:'protein', unit:1,
    a:'多條肽鏈並排形成的扇形二級結構。',
    detail:'平行 (parallel) 或反平行 (antiparallel) 兩種排列。鏈間靠骨架氫鍵連接。Greek key、jelly roll 是常見的 β-sheet 拓樸。' },
  { q:'loop', zh:'loop', tag:'結構', course:'protein', unit:1,
    a:'連接 helix / sheet 之間的不規則區段。',
    detail:'看似雜亂，但常常是活性中心。最靈活的 loop（B-factor 高）通常負責抓底物或介導交互作用。' },
  { q:'domain', zh:'蛋白質 domain', tag:'結構', course:'protein', unit:2,
    a:'蛋白中能獨立摺疊的功能模組。',
    detail:'常跨蛋白重複出現，例如 SH3、kinase domain、zinc finger。一個大蛋白往往由幾個 domain 串接，各司其職。' },
  { q:'tertiary structure', zh:'三級結構', tag:'結構', course:'protein', unit:2,
    a:'整條多肽鏈的最終 3D 摺疊。',
    detail:'由疏水核心、氫鍵、雙硫鍵、靜電作用共同維持。摺疊錯誤可造成疾病 — 例如阿茲海默 amyloid、prion。' },
  { q:'quaternary structure', zh:'四級結構', tag:'結構', course:'protein', unit:2,
    a:'多條多肽鏈組成的複合物。',
    detail:'血紅素 (hemoglobin) 是 2α + 2β 四聚體；ATP synthase 是分子機器級的多次單元複合物。' },
  { q:'disulfide bond', zh:'雙硫鍵', tag:'結構', course:'protein', unit:0,
    a:'兩個 Cys 殘基 SH 氧化形成 S-S 共價鍵。',
    detail:'常見於分泌蛋白與膜外 domain — 因為細胞外環境氧化、有利雙硫鍵形成。蛋白工程中常用引入雙硫鍵增加穩定性。' },
  { q:'PDB', zh:'蛋白質資料庫', tag:'結構', course:'protein', unit:3,
    a:'收錄實驗解析的生物大分子 3D 結構的公共資料庫。',
    detail:'每筆有 4 字元 PDB ID（例如 1HHO 血紅素、6VYB 新冠 spike）。文字格式 .pdb 或 .cif，逐行記錄原子座標。' },
  { q:'resolution', zh:'解析度', tag:'結構', course:'protein', unit:3,
    a:'X-ray 或 cryo-EM 結構的清晰度，單位 Å。',
    detail:'< 2.0 Å 非常清楚；2-3 Å 良好可信；> 3 Å 只能看大致摺疊。先看 resolution 再相信細節。' },
  { q:'AlphaFold', zh:'AlphaFold', tag:'結構', course:'protein', unit:5,
    a:'DeepMind 開發的蛋白質結構預測 AI 模型。',
    detail:'2020 AF2 在 CASP14 大幅超越所有傳統方法。核心 insight：從 MSA 學「演化共變」推測 3D 接觸。AlphaFold DB 已收 2 億條預測結構。' },
  { q:'pLDDT', zh:'pLDDT 信心度', tag:'結構', course:'protein', unit:5,
    a:'AlphaFold 逐殘基的預測信心分數 (0-100)。',
    detail:'> 90 非常可信、70-90 大致可信、< 50 通常是 IDR 而非錯誤。看 AlphaFold 結構前要先看 pLDDT 顏色圖。' },
  { q:'IDR', zh:'本質無序區', tag:'結構', course:'protein', unit:5,
    a:'沒有穩定 3D 摺疊的蛋白區段。',
    detail:'Intrinsically Disordered Region。常擔任「中樞 hub」介導多個交互作用，p53 transactivation domain 是經典例。' },
  { q:'BLOSUM (in folding)', zh:'保守殘基', tag:'結構', course:'protein', unit:5,
    a:'MSA 中跨物種高度保留的位置。',
    detail:'通常對應活性中心或結構關鍵殘基。設計突變實驗時，建議避開保守位點以免破壞功能。' },

  // ── NGS / 變異 ──
  { q:'NGS', zh:'次世代定序', tag:'NGS', course:'ngs', unit:0,
    a:'高通量並行定序技術的總稱。',
    detail:'Illumina 是主流短讀（150 bp）；PacBio HiFi、Oxford Nanopore 是長讀（kb 級）。長讀解 structural variant 與重複區更有利。' },
  { q:'FASTQ', zh:'FASTQ 格式', tag:'資料格式', course:'ngs', unit:4,
    a:'NGS reads 的標準格式，每條 4 行。',
    detail:'第 1 行 @id、第 2 行序列、第 3 行 +、第 4 行品質字串。品質用 Phred 分數編碼：Q20 = 1% 錯誤、Q30 = 0.1% 錯誤。' },
  { q:'FASTA', zh:'FASTA 格式', tag:'資料格式', course:'py', unit:1,
    a:'最通用的序列檔格式：> 標題 + 序列。',
    detail:'簡單到「不需要 schema」。生資 90% 的工具都接受 FASTA。Biopython SeqIO 可一行讀寫，並能轉換到 GenBank / FASTQ 等。' },
  { q:'read depth', zh:'讀取深度', tag:'NGS', course:'ngs', unit:3,
    a:'某位置被定序 reads 覆蓋的次數。',
    detail:'例：30× 覆蓋表示平均每個 base 有 30 條 reads。WES 建議 ≥ 100×、WGS ≥ 30×、RNA-seq 平均 30-50M reads/樣本即可。' },
  { q:'coverage', zh:'覆蓋率', tag:'NGS', course:'ngs', unit:3,
    a:'有 reads 對應到的基因組比例。',
    detail:'Depth 是「平均多深」；coverage 是「有多廣」。GC bias、重複序列、低複雜區常造成局部覆蓋不均，需要 QC 工具評估。' },
  { q:'SAM / BAM', zh:'SAM / BAM 格式', tag:'資料格式', course:'ngs', unit:5,
    a:'存放 reads 對齊結果的標準格式。',
    detail:'SAM 是文字、BAM 是二進位壓縮 (samtools view 可互轉)。每條 record 含 CIGAR string 標記 match/insertion/deletion/soft-clip。' },
  { q:'VCF', zh:'變異呼叫格式', tag:'資料格式', course:'var', unit:1,
    a:'記錄樣本變異的標準格式。',
    detail:'每列一個變異：染色體、位置、REF、ALT、品質、INFO、FORMAT、樣本基因型。bcftools / GATK 是主流工具鏈。' },
  { q:'SNP', zh:'單核苷酸多型性', tag:'NGS', course:'var', unit:0,
    a:'群體中某位點的單一核苷酸變異。',
    detail:'Minor Allele Frequency (MAF) > 1% 才算 SNP，否則稱「罕見變異」。GWAS 用 SNP 與表型做關聯研究找致病基因。' },
  { q:'INDEL', zh:'插入 / 刪除', tag:'NGS', course:'var', unit:0,
    a:'小規模的插入或刪除變異。',
    detail:'通常指 < 50 bp 的 indel；超過 50 bp 視為 structural variant。非 3n 的 indel 在編碼區造成 frameshift。' },
  { q:'CNV', zh:'拷貝數變異', tag:'NGS', course:'var', unit:0,
    a:'某區段在基因組中出現拷貝數差異。',
    detail:'例：唐氏症是第 21 號染色體三體 (trisomy 21)。CNV 在癌症基因組中極常見，例如 MYC 增幅、TP53 缺失。' },
  { q:'structural variant', zh:'結構變異', tag:'NGS', course:'var', unit:0,
    a:'> 50 bp 的大規模變異。',
    detail:'包含 deletion、insertion、duplication、inversion、translocation。長讀定序（PacBio、Nanopore）大幅提升 SV 偵測敏感度。' },
  { q:'MAF', zh:'最小等位基因頻率', tag:'統計', course:'var', unit:3,
    a:'群體中較少見的那個等位基因的頻率。',
    detail:'Minor Allele Frequency。MAF < 1% 通常稱罕見變異，需要特殊統計方法（如 SKAT、burden test）做關聯分析。' },

  // ── 表現分析 ──
  { q:'RNA-seq', zh:'RNA 定序', tag:'表現', course:'rnaseq', unit:0,
    a:'用 NGS 測 mRNA 來量化基因表現。',
    detail:'流程：mRNA → cDNA → 片段化 → 定序 → 對齊 → counts。輸出 counts matrix 是後續所有分析的起點。' },
  { q:'TPM', zh:'TPM 標準化', tag:'統計', course:'rnaseq', unit:1,
    a:'Transcripts Per Million，跨樣本可比的標準化。',
    detail:'TPM = (counts / 長度) / Σ(counts / 長度) × 10⁶。每樣本 TPM 加總 = 1M。比 FPKM 更適合跨樣本比較。' },
  { q:'FPKM / RPKM', zh:'FPKM / RPKM', tag:'統計', course:'rnaseq', unit:1,
    a:'較舊的 RNA-seq 標準化方法。',
    detail:'Fragments / Reads Per Kilobase per Million。先除樣本深度、再除長度。跨樣本不一定可比；現代論文多改用 TPM。' },
  { q:'log2FoldChange', zh:'log₂ 倍數變化', tag:'統計', course:'rnaseq', unit:2,
    a:'處理 vs 對照的倍數變化，取 log₂。',
    detail:'+1 = 翻倍上調，−1 = 減半下調。log₂ 讓上下調對稱，方便視覺化判斷。閾值常用 |log2FC| > 1（即 2 倍）。' },
  { q:'padj', zh:'校正後 p 值', tag:'統計', course:'rnaseq', unit:2,
    a:'多重檢定校正後的顯著性 (FDR)。',
    detail:'常用 Benjamini-Hochberg 校正。2 萬個基因同時檢定不校正會大量偽陽性。判讀差異表現一律看 padj < 0.05，不看 pvalue。' },
  { q:'DESeq2', zh:'DESeq2', tag:'表現', course:'rnaseq', unit:2,
    a:'R 套件，做 RNA-seq 差異表現分析。',
    detail:'核心模型是負二項分布；跨基因借資訊估離散度，比單基因獨立估更穩。輸出 log2FC、pvalue、padj。' },
  { q:'volcano plot', zh:'火山圖', tag:'表現', course:'rnaseq', unit:3,
    a:'橫 log2FC、縱 −log10(padj) 的散點圖。',
    detail:'右上 = 顯著上調，左上 = 顯著下調，下方 = 不顯著。是差異表現結果的標準呈現方式。' },
  { q:'GO', zh:'基因本體論', tag:'表現', course:'rnaseq', unit:4,
    a:'Gene Ontology，標註基因功能的標準分類。',
    detail:'三分支：BP (過程)、MF (功能)、CC (位置)。GO 富集分析回答「我的基因群是不是顯著集中在某個功能類別」。' },
  { q:'KEGG', zh:'KEGG 通路', tag:'表現', course:'rnaseq', unit:5,
    a:'代謝與訊息傳遞通路的手繪知識庫。',
    detail:'每張 pathway 圖把參與基因和分子的因果關係畫出來。可把 log2FC 上色到通路上，呈現上游 → 下游的機制故事。' },
  { q:'enrichment analysis', zh:'富集分析', tag:'統計', course:'rnaseq', unit:4,
    a:'測你的基因群是否顯著富集在某 term。',
    detail:'數學上是 Fisher exact / hypergeometric test。常見軟體：clusterProfiler、enrichR、DAVID、g:Profiler。' },
  { q:'scRNA-seq', zh:'單細胞 RNA-seq', tag:'表現', course:'sc', unit:0,
    a:'測單細胞解析度的基因表現。',
    detail:'10x Genomics 為主流。輸出是「細胞 × 基因」稀疏矩陣，每細胞約 1000-5000 個 detected genes。揭示細胞型態異質性。' },
  { q:'UMAP', zh:'UMAP 降維', tag:'統計', course:'sc', unit:3,
    a:'非線性降維方法，把高維壓到 2D。',
    detail:'保留局部相似結構，比 t-SNE 更快、群間距更有意義。scRNA-seq 必備視覺化工具。' },
  { q:'t-SNE', zh:'t-SNE', tag:'統計', course:'sc', unit:3,
    a:'另一種非線性降維方法。',
    detail:'比 UMAP 更早出現。優點：局部群聚清楚；缺點：群間距離無物理意義、運算慢、結果有隨機性。' },
  { q:'doublet', zh:'雙細胞', tag:'表現', course:'sc', unit:2,
    a:'scRNA-seq 中誤把兩個細胞當一個的事件。',
    detail:'10x 細胞密度越高，doublet 率越高（約 0.4% / 1000 cells）。Scrublet、DoubletFinder 可用 ML 估計並過濾。' },

  // ── 演化 / 群體 ──
  { q:'phylogeny', zh:'系統發生', tag:'演化', course:'phy', unit:0,
    a:'用序列差異推論演化關係的方法。',
    detail:'流程：取序列 → MSA → 選替換模型 → 建樹 → bootstrap → 視覺化。常用方法 NJ、ML、Bayesian。' },
  { q:'substitution model', zh:'替換模型', tag:'演化', course:'phy', unit:0,
    a:'描述鹼基如何隨時間替換的機率模型。',
    detail:'核酸：JC、K2P、HKY、GTR（複雜度遞增）。蛋白：PAM、BLOSUM、WAG。可用 ModelTest 自動選最合適的。' },
  { q:'UPGMA', zh:'UPGMA', tag:'演化', course:'phy', unit:1,
    a:'層次分群建樹法，假設等速演化。',
    detail:'最簡單但限制最大。葉子等高 (ultrametric)。當分子時鐘假設不成立時會給錯誤拓樸，實務多用 NJ / ML 取代。' },
  { q:'Neighbor Joining', zh:'NJ 鄰接法', tag:'演化', course:'phy', unit:2,
    a:'距離法建樹，不假設等速演化。',
    detail:'核心：用調整過的距離量 D_ij 避免長分支吸引。速度快、輸出 unrooted tree，需要 outgroup 定方向。' },
  { q:'Maximum Likelihood', zh:'最大似然法', tag:'演化', course:'phy', unit:3,
    a:'找最能解釋資料的樹拓樸 + 模型參數。',
    detail:'比距離法更精準，能利用每個位點資訊。代表軟體：RAxML、IQ-TREE。配合 ultrafast bootstrap 已成主流。' },
  { q:'bootstrap', zh:'Bootstrap 信心值', tag:'演化', course:'phy', unit:4,
    a:'對 MSA 欄位重抽 → 重建樹 → 看分支出現率。',
    detail:'≥ 70 可接受、≥ 95 很可信、< 50 不採信。UFBoot (IQ-TREE) 比傳統 bootstrap 快 50-100 倍，已成主流。' },
  { q:'outgroup', zh:'外群', tag:'演化', course:'phy', unit:2,
    a:'用來定根、定方向的較遠物種。',
    detail:'研究哺乳類時用鳥類或爬蟲類；研究人類用大猩猩。沒有 outgroup 的樹是 unrooted，看不出方向。' },
  { q:'molecular clock', zh:'分子時鐘', tag:'演化', course:'phy', unit:1,
    a:'假設突變累積的速率隨時間恆定。',
    detail:'UPGMA 的核心前提。實際上不同譜系、不同基因都不嚴格恆定 — 所以 ML 常採「relaxed clock」放鬆此假設。' },
  { q:'Hardy-Weinberg', zh:'哈溫平衡', tag:'統計', course:'pop', unit:0,
    a:'隨機交配族群中等位基因頻率不變的定律。',
    detail:'p² + 2pq + q² = 1。實務上用來檢查基因型數據品質：偏離 HWE 平衡常暗示族群分層或基因型呼叫錯誤。' },
  { q:'Fst', zh:'Fst 族群分化指數', tag:'統計', course:'pop', unit:2,
    a:'測量兩族群間遺傳分化的程度 (0-1)。',
    detail:'Fst = 0 → 完全相同；Fst > 0.15 通常代表顯著分化。比較人類各族群間 Fst 多在 0.05-0.15。' },
  { q:'allele frequency', zh:'等位基因頻率', tag:'統計', course:'pop', unit:1,
    a:'族群中某等位基因出現的比例。',
    detail:'是大多數群體遺傳指標的基礎。在小族群中受漂變影響大；大族群中天擇與遷移影響較主導。' },

  // ── 工具 ──
  { q:'conda', zh:'conda 環境管理', tag:'工具', course:'py', unit:0,
    a:'Python + 套件的隔離式環境管理器。',
    detail:'每專案一個 env 避免衝突。bioconda channel 收錄大量生資工具（samtools、bwa、salmon...）。Mamba 是更快的兼容工具。' },
  { q:'Biopython', zh:'Biopython', tag:'工具', course:'py', unit:2,
    a:'Python 的生資標準套件。',
    detail:'核心模組 Bio.Seq（序列物件）、Bio.SeqIO（讀寫 FASTA / GenBank）、Bio.Blast（呼叫 BLAST）、Bio.Phylo（樹）。' },
  { q:'pandas', zh:'pandas', tag:'工具', course:'py', unit:5,
    a:'Python 表格處理的標準套件。',
    detail:'核心物件 DataFrame，類似 Excel 表。生資 80% 的「結果後處理」（篩 padj、merge 註解、計平均）都靠 pandas。' },
  { q:'GenBank', zh:'GenBank 格式', tag:'資料格式', course:'py', unit:4,
    a:'NCBI 的綜合格式：序列 + 完整註解 features。',
    detail:'比 FASTA 多了 CDS / gene / mRNA / source 等 feature 標註，每個有 location 與 qualifiers。Biopython SeqIO 可解析。' },

  // ── 機器學習 ──
  { q:'supervised learning', zh:'監督式學習', tag:'統計', course:'ml', unit:0,
    a:'用「有標籤」資料訓練分類或回歸模型。',
    detail:'例：用已知致病/良性突變訓練 SIFT / PolyPhen。需要大量精準標註資料 — 在生資中標註成本高是常見瓶頸。' },
  { q:'one-hot encoding', zh:'One-hot 編碼', tag:'統計', course:'ml', unit:1,
    a:'把類別資料轉成 0/1 向量。',
    detail:'DNA 鹼基 one-hot：A=[1,0,0,0]、C=[0,1,0,0]、G=[0,0,1,0]、T=[0,0,0,1]。是深度學習處理序列輸入的標準前處理。' },
  { q:'AUROC', zh:'AUROC / AUC', tag:'統計', course:'ml', unit:5,
    a:'分類器在所有閾值下的整體性能指標 (0-1)。',
    detail:'0.5 = 隨機猜；> 0.8 通常算好。當資料不平衡時 (e.g. 致病變異稀少)，PR-AUC 比 AUROC 更具參考性。' },
];

Object.assign(window, { FLASHCARDS_FULL });
