// quiz-bank.jsx — expanded question bank, grouped by course

const QUIZ_BANK = [
  // ── intro ──
  { course:'intro', q:'下列哪一個是「品質分數編碼」的 Phred 規則？',
    opts:['Q10 代表 1% 錯誤率', 'Q20 代表 1% 錯誤率', 'Q30 代表 1% 錯誤率', 'Q40 代表 1% 錯誤率'],
    correct:1,
    note:'Phred Q = -10·log₁₀(P)。Q20 → 10⁻² = 1% 錯誤；Q30 → 0.1%；Q10 → 10%。' },
  { course:'intro', q:'下列哪一個檔案儲存「reads 對齊到參考」的結果？',
    opts:['.fasta', '.fastq', '.bam', '.vcf'],
    correct:2,
    note:'.bam 是 reads 對齊後的二進位格式；.fastq 是原始 reads、.vcf 是變異呼叫結果。' },
  { course:'intro', q:'要查某基因的人類同源序列，最方便的入口是？',
    opts:['UCSC Genome Browser', 'NCBI / Ensembl', 'PDB', 'gnomAD'],
    correct:1,
    note:'NCBI 與 Ensembl 都提供基因註解與同源資訊；UCSC 強在視覺化；PDB 是結構；gnomAD 是變異頻率。' },

  // ── dna ──
  { course:'dna', q:'下列哪一個 mRNA 密碼子代表「起始」？',
    opts:['AUG', 'UAA', 'UGA', 'GCC'],
    correct:0,
    note:'AUG (Methionine) 是真核生物的起始密碼子；UAA / UGA 是終止密碼子。' },
  { course:'dna', q:'若一段 DNA 的 GC 含量為 60%，則 A 約佔多少？',
    opts:['10%', '20%', '30%', '40%'],
    correct:1,
    note:'GC=60% 表示 AT=40%；A 與 T 各約一半，所以 A ≈ 20%。' },
  { course:'dna', q:'5\'-ATCG-3\' 的反向互補是？',
    opts:['TAGC', 'CGTA', 'CGAT', 'GCTA'],
    correct:2,
    note:'先互補：TAGC；再反轉：CGAT。注意是「先互補、再反轉」兩個步驟。' },
  { course:'dna', q:'下列哪種突變對蛋白功能影響「通常最嚴重」？',
    opts:['Silent', 'Conservative missense', 'Frameshift (1 bp insertion)', 'Synonymous'],
    correct:2,
    note:'非 3n 的 indel 造成 frameshift，從該點以後密碼子全部錯位，幾乎必然產生無功能蛋白。' },
  { course:'dna', q:'下列何者「不是」轉錄產物 (mRNA) 的加工步驟？',
    opts:['5\' capping', 'PolyA tailing', 'Splicing', 'Reverse complementation'],
    correct:3,
    note:'反向互補不是 mRNA 加工步驟。前三項都是真核 pre-mRNA → 成熟 mRNA 的必要修飾。' },

  // ── aln ──
  { course:'aln', q:'BLAST 結果 E-value = 1e-50 與 E-value = 0.1 比較，哪個比較顯著？',
    opts:['E-value 較大者', 'E-value = 0.1', 'E-value = 1e-50', '兩者相同'],
    correct:2,
    note:'E-value 越小代表偶然出現的機率越低，因此 1e-50 遠比 0.1 顯著。' },
  { course:'aln', q:'要找「兩條序列中最相似的子片段」，應該用？',
    opts:['Needleman-Wunsch (global)', 'Smith-Waterman (local)', 'UPGMA', 'PCA'],
    correct:1,
    note:'Smith-Waterman 是局部比對，能找出最相似的子片段；NW 強制端到端對齊。' },
  { course:'aln', q:'BLAST 為什麼比完整 SW 快很多？',
    opts:['BLAST 用較小資料庫', '用 seed-and-extend 先粗篩 k-mer', '直接跳過 alignment 計算', '用 GPU 加速'],
    correct:1,
    note:'BLAST 先在資料庫中找 k-mer 相符 (用 hash table 極快)，再向兩側延伸做局部比對 — 這就是 seed-and-extend。' },
  { course:'aln', q:'MSA 在系統發生分析中的角色為？',
    opts:[
      '把序列依長度排序',
      '把同源位點對齊以估計演化距離',
      '只是讓圖好看',
      '直接畫出演化樹',
    ],
    correct:1,
    note:'MSA 把同源位點對齊後，才能逐欄比較差異並計算演化距離 → 進而建樹。' },
  { course:'aln', q:'BLOSUM62 計分矩陣是從哪裡得到的？',
    opts:['手工指定', '同源性 ≥ 62% 的序列家族統計', 'BLAST 內建', '隨機初始化'],
    correct:1,
    note:'BLOSUM (Blocks Substitution Matrix) 是從序列同源性 ≥ 62% 的家族中統計各胺基酸替換頻率得到。' },

  // ── protein ──
  { course:'protein', q:'α-helix 的氫鍵是在哪兩個位置之間形成？',
    opts:['i 與 i+1', 'i 與 i+4', 'i 與 i+7', '相鄰兩條鏈'],
    correct:1,
    note:'α-helix 由「i 與 i+4」位置的骨架氫鍵穩定，每圈約 3.6 殘基。β-sheet 的氫鍵則發生在「相鄰兩條鏈之間」。' },
  { course:'protein', q:'AlphaFold 預測結構中 pLDDT < 50 的區段最可能是？',
    opts:['預測錯誤', '本質無序區 (IDR)', '雙硫鍵密集區', '訊號胜肽'],
    correct:1,
    note:'低 pLDDT 通常並非錯誤，而是真正的 IDR（intrinsically disordered region） — 本身就沒有固定 3D 結構。' },
  { course:'protein', q:'下列哪一類胺基酸最可能位於蛋白「內部疏水核心」？',
    opts:['Lys / Arg / His', 'Asp / Glu', 'Leu / Val / Ile', 'Ser / Thr'],
    correct:2,
    note:'疏水殘基（Leu、Val、Ile、Phe...）會躲到內部核心；極性與帶電殘基翻到表面接觸水。' },
  { course:'protein', q:'下列何者是「四級結構」的範例？',
    opts:[
      '一條多肽鏈摺成 3D',
      '兩條多肽鏈組成功能複合物',
      'α-helix 與 β-sheet',
      '胺基酸序列',
    ],
    correct:1,
    note:'四級結構是多條多肽鏈組成複合物 (oligomer)，例如血紅素 (2α+2β)。' },

  // ── ngs ──
  { course:'ngs', q:'下列何者「不是」NGS 平台？',
    opts:['Illumina NovaSeq', 'PacBio Sequel', 'Sanger ABI 3730', 'Oxford Nanopore'],
    correct:2,
    note:'Sanger 是第一代毛細管電泳定序，不屬於次世代。其餘三者都是 NGS / long-read NGS。' },
  { course:'ngs', q:'WGS 建議的最低 read depth (coverage) 通常是？',
    opts:['3×', '10×', '30×', '300×'],
    correct:2,
    note:'WGS 標準 30× 可信賴呼叫 SNV/INDEL；WES 因為僅針對外顯子，建議 100× 以上。' },
  { course:'ngs', q:'BAM 檔的索引檔副檔名是？',
    opts:['.bai', '.bed', '.fai', '.tbi'],
    correct:0,
    note:'.bai 是 BAM 索引；.fai 是 FASTA 索引；.tbi 是 tabix (常用於 .vcf.gz)。' },
  { course:'ngs', q:'FASTQ 第三行的 "+" 主要功能是？',
    opts:['分隔符', '註解', '另一條 reads', '品質開始標誌'],
    correct:0,
    note:'第三行的 + 純粹作為分隔符，分開序列行與品質行。早期會放重複的 ID，現在大多省略。' },

  // ── var ──
  { course:'var', q:'VCF 中 0/1 代表什麼？',
    opts:['沒有變異', '同型 REF', '異型（一個 REF、一個 ALT）', '同型 ALT'],
    correct:2,
    note:'0/1 = 異型；0/0 = 同型 REF；1/1 = 同型 ALT。對應到「兩個等位基因」的組合。' },
  { course:'var', q:'gnomAD 上某變異 popmax MAF = 5%，這代表？',
    opts:[
      '極可能是孟德爾致病罕見變異',
      '通常視為良性常見變異',
      'GWAS 應排除這個變異',
      'ClinVar 未收錄',
    ],
    correct:1,
    note:'高 MAF 變異難以解釋孟德爾遺傳病（病應該稀少）。臨床診斷常做 popmax filter：任族群 MAF > 1% 視為良性。' },
  { course:'var', q:'GATK 流程中，BQSR (Base Quality Score Recalibration) 應放在哪一步之後？',
    opts:['BWA 對齊', 'MarkDuplicates', 'HaplotypeCaller', 'VQSR'],
    correct:1,
    note:'順序：BWA → MarkDuplicates → BQSR → HaplotypeCaller → VQSR。BQSR 必須在去重之後、呼叫變異之前。' },
  { course:'var', q:'ClinVar 「★ 4 顆星」的變異代表什麼？',
    opts:[
      '一個實驗室提交',
      '多源證據一致',
      '極致病',
      '極良性',
    ],
    correct:1,
    note:'星級代表「證據強度」，不是「致病性強度」。4 星 = expert panel 共識；2-3 星 = 多源一致；1 星 = 單一來源。' },

  // ── rnaseq ──
  { course:'rnaseq', q:'RNA-seq 火山圖中，「右上角」的點通常代表？',
    opts:['顯著上調的基因', '顯著下調的基因', '不顯著的基因', '低表達雜訊'],
    correct:0,
    note:'橫軸 log₂FC 為正、縱軸 −log₁₀(p) 大 → 顯著上調。負側為下調。' },
  { course:'rnaseq', q:'下列哪個標準化「跨樣本」最適合比較？',
    opts:['raw counts', 'FPKM', 'TPM', 'RPM'],
    correct:2,
    note:'TPM 每樣本加總一定是 10⁶，跨樣本可直接比較。FPKM/RPKM 的總和不一定相等，跨樣本比較有偏差。' },
  { course:'rnaseq', q:'DESeq2 使用的統計分布是？',
    opts:['Normal', 'Poisson', 'Negative Binomial', 'Beta'],
    correct:2,
    note:'RNA-seq counts 的變異大於 Poisson 預期（過度離散），所以 DESeq2 用負二項分布。' },
  { course:'rnaseq', q:'「padj < 0.05」中的 padj 指的是？',
    opts:[
      '原始 p 值',
      '多重檢定校正後的 p 值 (FDR)',
      '半邊 p 值',
      '貝氏後驗',
    ],
    correct:1,
    note:'padj = adjusted p-value，通常用 BH 方法做 FDR 校正。差異表現一律看 padj，不看 raw pvalue。' },
  { course:'rnaseq', q:'GO 富集分析常用的統計檢定是？',
    opts:['t-test', 'Fisher / hypergeometric test', 'Chi-square', 'ANOVA'],
    correct:1,
    note:'GO 富集問「某 term 在我的基因群比例是否顯著高於背景」 — 是分類資料比較，用 Fisher 精確 / 超幾何檢定。' },

  // ── sc ──
  { course:'sc', q:'10x scRNA-seq 中每個微滴 (GEM) 包了什麼？',
    opts:['一個細胞核', '一個細胞 + 一顆條碼磁珠', '兩個細胞', '一個 mRNA 分子'],
    correct:1,
    note:'每個 GEM 內含一個細胞與一顆攜帶獨特 cell barcode 的磁珠 — 之後合併測序靠 barcode 還原細胞身分。' },
  { course:'sc', q:'scRNA-seq UMAP 之前必須先做什麼？',
    opts:['VCF 過濾', 'PCA 降維', 'BWA 對齊', 'Bootstrap'],
    correct:1,
    note:'PCA 把 20K 基因降到 30-50 維，去除主要雜訊。直接對全基因矩陣做 UMAP 會極慢且失真。' },
  { course:'sc', q:'下列哪個指標太高代表「細胞膜破裂」？',
    opts:[
      'Detected gene count',
      'UMI count',
      '% mitochondrial reads',
      'Cell barcode 數',
    ],
    correct:2,
    note:'破裂細胞會漏出細胞質、保留粒線體，因此粒線體 reads 比例升高。閾值常設 10-20%。' },

  // ── phy ──
  { course:'phy', q:'Bootstrap = 95 的分支代表？',
    opts:[
      '該分支樹拓樸的真實機率是 95%',
      '100 次重抽中該分支出現 95 次',
      '該分支演化速率比其他快 95%',
      '該分支序列同源性 95%',
    ],
    correct:1,
    note:'Bootstrap 是對 MSA 欄位重抽後重建樹，看每個分支出現的「頻率」。≥ 95 一般視為非常可信。' },
  { course:'phy', q:'下列哪一個建樹法「假設等速演化」？',
    opts:['UPGMA', 'Neighbor Joining', 'Maximum Likelihood', 'Bayesian'],
    correct:0,
    note:'UPGMA 假設分子時鐘 (等速演化)，葉子等高。NJ / ML / Bayesian 都不需要此前提。' },
  { course:'phy', q:'NJ 輸出的樹預設是？',
    opts:['Rooted tree', 'Unrooted tree', 'Time-calibrated tree', 'Ultrametric tree'],
    correct:1,
    note:'NJ 是 unrooted；要看演化方向需要 outgroup 定根。Ultrametric 則是 UPGMA 的特性。' },
  { course:'phy', q:'要看樹的「演化方向」，你需要什麼？',
    opts:['Bootstrap 值', 'Outgroup', '替換模型', 'MSA'],
    correct:1,
    note:'Outgroup 是離研究組相對較遠的物種，用來「定根」。沒有 outgroup 的樹只能看分群關係，無法定方向。' },

  // ── pop ──
  { course:'pop', q:'Hardy-Weinberg 平衡公式是？',
    opts:['p + q = 1', 'p² + 2pq + q² = 1', 'p · q = 0.5', 'pq + p + q = 1'],
    correct:1,
    note:'p² + 2pq + q² = 1 — AA + Aa + aa 基因型頻率總和為 1。' },
  { course:'pop', q:'GWAS 前處理通常會過濾 HWE 偏離過大的 SNP，原因是？',
    opts:[
      '這些 SNP 一定致病',
      '常暗示基因型呼叫錯誤或樣本污染',
      '為了縮小資料量',
      '為了滿足假設前提',
    ],
    correct:1,
    note:'偏離 HWE 常代表呼叫品質有問題、族群分層、或樣本污染。GWAS 通常用 HWE p < 1e-6 之類的閾值過濾。' },
  { course:'pop', q:'人類族群間（洲際）的 Fst 大約落在？',
    opts:['0.01', '0.05-0.15', '0.4-0.6', '> 0.8'],
    correct:1,
    note:'人類各大洲族群間 Fst ≈ 0.05-0.15。這就是「人類遺傳變異 ~85% 在族群內、15% 在族群間」的數字基礎。' },

  // ── py ──
  { course:'py', q:'Biopython 讀 FASTA 的最常用方法是？',
    opts:['SeqIO.parse', 'AlignIO.read', 'SearchIO.parse', 'Phylo.parse'],
    correct:0,
    note:'SeqIO.parse 回傳迭代器，邊讀邊處理，大檔不爆記憶體。' },
  { course:'py', q:'pandas 中，下列哪一個是「篩選列」最常用的寫法？',
    opts:[
      'df.filter(col == 1)',
      'df[df.col > 5]',
      'df.where(col)',
      'df.col.greater(5)',
    ],
    correct:1,
    note:'Boolean mask：df[df.col > 5] 是 pandas 篩選列最常見的寫法。' },
  { course:'py', q:'conda 建環境的指令是？',
    opts:[
      'pip install -e bioenv',
      'conda create -n bioenv python=3.11',
      'conda new bioenv',
      'python -m venv bioenv',
    ],
    correct:1,
    note:'conda create -n NAME python=VERSION 建立新環境；activate / deactivate 切換。' },
  { course:'py', q:'要把 Python 翻譯 DNA 轉成蛋白序列，Biopython 怎麼做？',
    opts:[
      'Seq("ATG").to_protein()',
      'Seq("ATG").translate()',
      'Seq("ATG").convert("protein")',
      'protein(Seq("ATG"))',
    ],
    correct:1,
    note:'Seq 物件的 .translate() 方法。可帶 table 參數選擇密碼子表（粒線體用不同表）。' },

  // ── r ──
  { course:'r', q:'R 中對 p 值做 BH (FDR) 校正的函數是？',
    opts:['adjust.p()', 'p.adjust(p, method="BH")', 'fdr.adjust()', 'multcomp(p)'],
    correct:1,
    note:'p.adjust(p, method="BH") 是標準寫法。RNA-seq、GWAS 的多重檢定校正幾乎都是 BH。' },
  { course:'r', q:'tidyverse 的管線運算符是？',
    opts:['|', '%>%', '->>', '~~'],
    correct:1,
    note:'tidyverse 用 %>%（magrittr 提供）；R 4.1+ 原生支援 |>，與 %>% 行為大致一致。' },
  { course:'r', q:'ggplot 中改變座標軸標籤用哪個函數？',
    opts:['labs()', 'title()', 'axis()', 'xlab() + ylab()'],
    correct:0,
    note:'labs(x=..., y=..., title=...) 是最完整的標題與軸標籤設定；xlab/ylab 也可，但 labs 更常見。' },

  // ── ml ──
  { course:'ml', q:'DNA 序列輸入 CNN 模型，最標準的編碼是？',
    opts:['ASCII 編碼', 'One-hot 編碼 (4 通道)', 'PCA 投影', 'BERT embedding'],
    correct:1,
    note:'A=[1,0,0,0]、C=[0,1,0,0]、G=[0,0,1,0]、T=[0,0,0,1]。CNN 處理 DNA 的標準輸入格式。' },
  { course:'ml', q:'下列哪一個任務是「非監督式學習」？',
    opts:[
      '預測變異致病性 (B/P)',
      'scRNA-seq 細胞分群',
      '預測蛋白質結構',
      '預測啟動子位點',
    ],
    correct:1,
    note:'分群沒有預先標籤，是非監督式。其他三個都有標籤 (致病/良性、座標、是否啟動子)。' },
  { course:'ml', q:'資料極不平衡（正樣本稀少）時，比 ROC-AUC 更具參考性的指標是？',
    opts:['Accuracy', 'PR-AUC', 'F-test', 'BLEU'],
    correct:1,
    note:'當正樣本稀少時 ROC-AUC 可能虛高；PR-AUC（Precision-Recall）能更真實反映模型在「找出稀少正例」上的表現。' },

  // ── 補題 (額外覆蓋) ──
  { course:'intro', q:'下列哪一個對應 Phred Q30 的錯誤率？',
    opts:['10%', '1%', '0.1%', '0.01%'],
    correct:2,
    note:'Phred Q = -10·log₁₀(P)。Q30 → 10⁻³ = 0.1% 錯誤率。WGS / RNA-seq 一般以 Q30 為品質基準。' },
  { course:'intro', q:'下列哪個檔案最適合用來「視覺化基因組訊號軌跡」（如 ChIP-seq peaks）？',
    opts:['.fa', '.bw / .wig', '.fastq', '.vcf'],
    correct:1,
    note:'.bw (BigWig) / .wig 專門儲存基因組位置上的連續訊號值，UCSC / IGV 都能直接顯示為 track。' },

  { course:'dna', q:'下列哪一個是 DNA → RNA 過程中的「正確」對應？',
    opts:['DNA: T → RNA: A', 'DNA: T → RNA: U', 'DNA: A → RNA: U', 'DNA: G → RNA: A'],
    correct:1,
    note:'RNA 用 U 取代 T；其他鹼基不變。所以 DNA 模板鏈上的 A → RNA 上 U（互補），而 DNA 上 T → RNA 上 A — 但題目問的是「字母上的替換」對應，DNA 上 T → RNA 上 U 是正確規則。' },
  { course:'dna', q:'下列何者「不是」終止密碼子？',
    opts:['UAA', 'UAG', 'UGA', 'UGG'],
    correct:3,
    note:'UAA / UAG / UGA 是三個終止碼；UGG 編碼 Tryptophan (Trp)，是正常胺基酸碼。' },

  { course:'aln', q:'下列哪個工具屬於「BLAST 家族成員」，用蛋白 query 對翻譯後的 DNA 資料庫？',
    opts:['blastn', 'blastp', 'blastx', 'tblastn'],
    correct:3,
    note:'tblastn：蛋白 query → 翻譯後的 DNA 資料庫；blastx 反向（DNA query → 蛋白資料庫）；blastn 是核酸 vs 核酸；blastp 是蛋白 vs 蛋白。' },

  { course:'protein', q:'蛋白質「四級結構」例子是？',
    opts:['α-helix 摺起來', '兩條多肽組成複合物', 'Cys 形成雙硫鍵', '胺基酸序列'],
    correct:1,
    note:'四級結構 = 多條多肽鏈組成 oligomer。血紅素 2α+2β、ATP synthase 為經典例。' },

  { course:'sc', q:'下列哪一個指標太「低」常代表「空 droplet 或死細胞」？',
    opts:['UMI counts', '% mitochondrial reads', 'doublet score', 'cell barcode 數'],
    correct:0,
    note:'UMI counts 太低 → 細胞死亡或捕獲失敗。% mito 太高才是膜破裂的訊號。' },
  { course:'sc', q:'下列何者「不適合」用來預測 scRNA-seq doublet？',
    opts:['Scrublet', 'DoubletFinder', 'scDblFinder', 'BWA'],
    correct:3,
    note:'BWA 是 reads 對齊工具，不是 doublet 偵測。其他三者都是專門偵測 doublet 的工具。' },

  { course:'phy', q:'用 IQ-TREE 預設的快速 bootstrap 替代品叫做？',
    opts:['SH-aLRT', 'UFBoot', 'Jackknife', 'Bayesian'],
    correct:1,
    note:'UFBoot (Ultrafast Bootstrap) 比傳統 bootstrap 快 50-100×，IQ-TREE 預設使用，現代主流。' },

  { course:'pop', q:'GWAS 為什麼要做 PCA？',
    opts:['加速計算', '校正族群分層 (stratification)', '降維視覺化', '提高 read depth'],
    correct:1,
    note:'PCA 把主要族群結構抽取出來當共變量，避免「族群差異」被誤認為「致病關聯」。' },
  { course:'pop', q:'下列哪個事件會「快速降低」族群中等位基因多樣性？',
    opts:['正向天擇', '族群瓶頸 (bottleneck)', '隨機交配', '基因流動'],
    correct:1,
    note:'瓶頸事件大量縮減族群，許多等位基因因抽樣機率而流失，多樣性驟降。漂變影響在瓶頸後特別顯著。' },

  { course:'py', q:'pandas 中「合併兩張表」的方法是？',
    opts:['concat', 'combine', 'merge / join', 'group_by'],
    correct:2,
    note:'merge / join 用於 SQL 風格的合併（依 key）；concat 是堆疊；groupby 是分組統計。' },

  { course:'r', q:'tidyverse 中專責「資料處理」(篩、選、變、組、總) 的套件是？',
    opts:['ggplot2', 'dplyr', 'tidyr', 'readr'],
    correct:1,
    note:'dplyr 提供 filter / select / mutate / group_by / summarise 等動詞；tidyr 偏資料整形；ggplot2 繪圖；readr 讀檔。' },

  { course:'ml', q:'蛋白質語言模型 (ESM、ProtBERT) 的訓練任務通常是？',
    opts:['監督式分類', 'Masked language modelling (隨機遮蔽再預測)', 'GAN', 'Reinforcement learning'],
    correct:1,
    note:'類似 BERT — 隨機遮住胺基酸要求模型預測。學到的 embedding 隱含結構、功能、共演化資訊。' },

  { course:'rnaseq', q:'下列哪一個「不」適合用來做 RNA-seq 對齊？',
    opts:['STAR', 'HISAT2', 'Salmon', 'BWA'],
    correct:3,
    note:'BWA 是給 DNA / WGS 用的，不知道 splice junction。STAR / HISAT2 是專門針對 RNA 的 splice-aware aligner；Salmon 是 quasi-mapping 不是傳統對齊但仍能算 quant。' },

  { course:'var', q:'GATK4 比 GATK3 最大的演進是？',
    opts:[
      '完全 GUI 化',
      'Java 全面改寫 + Spark 加速',
      '不需要 BWA',
      '取消 BQSR',
    ],
    correct:1,
    note:'GATK 4.x 全面用 Java 改寫、整合 Picard、支援 Spark 平行處理。BQSR / VQSR 等步驟保留。' },

  // ── 第三批補題（達 100+ 題）──
  { course:'dna', q:'下列何者「不是」DNA 與 RNA 的差異？',
    opts:['糖：去氧核糖 vs 核糖', '鹼基：T vs U', '單股 vs 雙股', '存在於 DNA 才有的胺基酸'],
    correct:3,
    note:'胺基酸不存在於核酸序列中 — 它是蛋白質的單位。前三項都是 DNA / RNA 結構上的差別。' },
  { course:'dna', q:'真核 pre-mRNA 從合成到輸出細胞質，「不」需要哪一個加工步驟？',
    opts:['5\' capping', 'PolyA tailing', 'Splicing', 'Reverse transcription'],
    correct:3,
    note:'反轉錄是 RNA → DNA 的方向，由反轉錄酶執行（HIV、LINE 元件），不是正常 mRNA 加工步驟。' },
  { course:'dna', q:'如果一段 100 bp DNA 含 25 A、35 G、25 C、15 T — 這條 DNA 的特徵是？',
    opts:['正常雙股 DNA', '單股 DNA 或 RNA', '為 cDNA', '已退化'],
    correct:1,
    note:'雙股 DNA 應該滿足 Chargaff 規則（A=T、G=C）。這條 A≠T、G≠C → 是單股序列（可能是 mRNA 反轉錄前或單股檔）。' },
  { course:'dna', q:'轉錄方向：RNA polymerase 沿模板鏈讀的方向是？',
    opts:['5\' → 3\'', '3\' → 5\'', '兩個方向都可以', '從 stop 開始'],
    correct:1,
    note:'酵素沿模板鏈 3\'→5\' 讀，合成 RNA 5\'→3\'。所有聚合酶都只能往 5\'→3\' 合成。' },

  { course:'aln', q:'BLOSUM 矩陣與 PAM 矩陣的主要差別是？',
    opts:['BLOSUM 較舊', 'BLOSUM 從手工對齊估計', 'BLOSUM 從序列家族統計、PAM 從演化模型推導', '兩者完全相同'],
    correct:2,
    note:'BLOSUM 直接從序列同源家族 (blocks) 統計替換頻率；PAM 以演化模型 (PAM1) 為基礎再延伸（PAM250 等）。現代多用 BLOSUM62。' },
  { course:'aln', q:'多序列比對 (MSA) 的結果可以用來做什麼下游分析？（複選最佳）',
    opts:[
      '建系統發生樹',
      '訓練 HMM profile',
      '找保守 motif',
      '以上皆是',
    ],
    correct:3,
    note:'MSA 是系統發生、profile-based 比對、motif 發現的共同入口。' },

  { course:'protein', q:'下列哪個工具最適合「視覺化蛋白質 3D 結構並產生發表圖」？',
    opts:['BLAST', 'PyMOL', 'GATK', 'samtools'],
    correct:1,
    note:'PyMOL 是分子結構視覺化標準軟體。BLAST 是比對、GATK 是變異呼叫、samtools 是 BAM 操作。' },
  { course:'protein', q:'某蛋白 AlphaFold 預測整體 pLDDT 平均 92，這代表？',
    opts:[
      '預測幾乎可靠當實驗用',
      '預測極不可靠',
      '蛋白功能未知',
      'pLDDT 已超出範圍',
    ],
    correct:0,
    note:'pLDDT > 90 表示結構預測非常可信，可當作高品質結構使用（單一靜態構象）。' },

  { course:'ngs', q:'WES (Whole Exome Sequencing) 建議的最低深度約是？',
    opts:['10×', '30×', '100×', '1000×'],
    correct:2,
    note:'WES 因為只捕獲外顯子，雜訊 / 雜亂高，需要 100× 以上才能可靠呼叫變異。WGS 30× 即可。' },
  { course:'ngs', q:'下列哪一個是 BAM 的索引檔副檔名？',
    opts:['.bam.idx', '.bai', '.fai', '.tbi'],
    correct:1,
    note:'.bai 是 BAM 索引（samtools index 生成）。.fai 是 FASTA、.tbi 是 tabix。' },
  { course:'ngs', q:'長讀定序（PacBio、Nanopore）的相對優勢是？',
    opts:[
      '價格便宜',
      '錯誤率極低',
      '對結構變異 (SV) 與重複區偵測敏感度高',
      '完全取代 Illumina',
    ],
    correct:2,
    note:'長讀能跨越重複序列、複雜區段，大幅改善 SV 偵測。但平均錯誤率高於 Illumina (約 1-2%)。HiFi 已改善許多。' },

  { course:'var', q:'下列何者「不」屬於 ACMG 變異判讀指引中的證據強度等級？',
    opts:['PVS1', 'PS1', 'PM2', 'BP4'],
    correct:0,
    note:'ACMG 等級碼形式：PVS (very strong)、PS (strong)、PM (moderate)、PP (supporting)、BS / BP (benign 對等)。PVS1 確實存在 — 此題其實所有選項都是合法等級，注意陷阱題。實務上 PVS1 = 蛋白截短性變異。' },
  { course:'var', q:'gnomAD 上「popmax MAF」的意思是？',
    opts:[
      '所有族群平均 MAF',
      '任一族群中最大的 MAF',
      '美國族群的 MAF',
      '臨床族群的 MAF',
    ],
    correct:1,
    note:'popmax MAF = max(MAF across populations)。臨床診斷時用此值做 filter：popmax > 1% 通常視為良性常見變異。' },

  { course:'rnaseq', q:'下列何者「不」適合處理 RNA-seq alignment？',
    opts:['STAR', 'HISAT2', 'TopHat2', 'BWA-MEM'],
    correct:3,
    note:'BWA-MEM 是給 DNA / WGS / WES 用的，不知道 RNA 的 splice junction。RNA 要用 splice-aware 對齊工具。' },
  { course:'rnaseq', q:'log2FC = 2 代表處理組是對照組的幾倍？',
    opts:['2 倍', '4 倍', '8 倍', '0.5 倍'],
    correct:1,
    note:'log₂(4) = 2，所以 log2FC = 2 代表 4 倍。同理 log2FC = 3 代表 8 倍。' },
  { course:'rnaseq', q:'DESeq2 的「shrinkage」(LFC shrinkage) 主要解決什麼問題？',
    opts:[
      '低表達基因的 log2FC 估計過於波動',
      '高表達基因被低估',
      '樣本間批次效應',
      '減少計算量',
    ],
    correct:0,
    note:'低 counts 基因雜訊大，naive log2FC 容易出現極大值。shrinkage 把這些朝零方向「收縮」，給更穩健的估計。' },

  { course:'sc', q:'PCA 在 scRNA-seq 流程中的「主要目的」是？',
    opts:[
      '視覺化',
      '降低噪音與維度，作為後續 UMAP / clustering 的輸入',
      '取代差異表現分析',
      '校正 dropout',
    ],
    correct:1,
    note:'PCA 把 20K 基因壓到 30-50 PC，去除大量雜訊與冗餘訊號。下游 KNN / UMAP / clustering 都在 PC 空間操作。' },
  { course:'sc', q:'Leiden 演算法在 scRNA-seq 中的用途是？',
    opts:['降維', '細胞分群', '差異表現', '軌跡分析'],
    correct:1,
    note:'Leiden 是社群偵測 (community detection) 演算法，在 KNN graph 上找出細胞群。比舊版 Louvain 更穩定。' },

  { course:'phy', q:'下列哪個是「unrooted tree」的特性？',
    opts:[
      '葉子等高',
      '沒有指定演化方向 / 根節點',
      '一定是用 ML 建的',
      '只能有兩個物種',
    ],
    correct:1,
    note:'Unrooted tree 沒有定向。NJ 預設輸出 unrooted；要看演化方向需要 outgroup 定根。' },
  { course:'phy', q:'Maximum Likelihood 比 NJ 的主要優勢是？',
    opts:[
      '計算更快',
      '不需要 MSA',
      '充分利用每個位點的資訊，精度通常較高',
      '不需要替換模型',
    ],
    correct:2,
    note:'ML 直接從序列位點計算機率；NJ 只用距離摘要。代價：ML 運算量大很多。現代軟體 RAxML / IQ-TREE 已能跑大資料。' },

  { course:'pop', q:'Hardy-Weinberg 平衡的五個前提中，「下列哪一個」「不是」前提？',
    opts:['隨機交配', '無遷移', '族群夠大', '所有等位基因頻率相等'],
    correct:3,
    note:'HWE 並不要求 p = q = 0.5。它只要求滿足：隨機交配、無天擇、無遷移、無突變、族群夠大。' },
  { course:'pop', q:'下列哪個情境最可能造成 Fst 接近 0？',
    opts:[
      '兩族群長期隔離',
      '兩族群間有頻繁基因流動',
      '兩族群是不同物種',
      '小族群 + 強漂變',
    ],
    correct:1,
    note:'基因流動 (migration) 讓兩族群的等位基因頻率趨同，Fst 接近 0。隔離與漂變則拉開 Fst。' },

  { course:'py', q:'下列哪一個是「pandas DataFrame」的方法，不是「pandas Series」的方法？',
    opts:['head()', 'mean()', 'merge()', 'sum()'],
    correct:2,
    note:'merge 是「合併兩張表」，只在 DataFrame 上有意義。其他方法 Series 也有。' },
  { course:'py', q:'用 Biopython 的 `seq.translate()` 時，要指定哪個參數使用「粒線體密碼子表」？',
    opts:['table="mt"', 'table=2', 'genetic_code=2', 'codon="mito"'],
    correct:1,
    note:'translate(table=2) 使用脊椎動物粒線體密碼子表（人粒線體 AGA/AGG 是 STOP，不是 Arg）。' },

  { course:'r', q:'下列哪一個 ggplot2 函數能畫熱圖？',
    opts:['geom_point', 'geom_tile', 'geom_smooth', 'geom_density'],
    correct:1,
    note:'geom_tile 把矩陣畫成色塊熱圖；geom_raster 是高效版本。配合 fill 美學映射數值。' },
  { course:'r', q:'Bioconductor 中專門做差異表現的套件「不」包括？',
    opts:['DESeq2', 'edgeR', 'limma', 'dplyr'],
    correct:3,
    note:'dplyr 是 tidyverse 中的資料處理套件，不是 Bioconductor 差異表現套件。前三者都是 RNA-seq DE 主流。' },

  { course:'ml', q:'下列哪一個是「集成學習 ensemble」的代表？',
    opts:['SVM', 'Random Forest', 'KNN', 'Logistic Regression'],
    correct:1,
    note:'Random Forest 集成多棵決策樹投票。其他三者是單一模型，但都可以做集成（如 ensemble of SVMs）。' },
  { course:'ml', q:'CNN 在 DNA 序列上學到的「卷積核」(kernel) 通常對應什麼生物意義？',
    opts:['密碼子表', 'TF 結合 motif 或序列特徵', 'codon usage bias', '甲基化位點'],
    correct:1,
    note:'CNN 卷積核掃過序列產生 activation peaks — 它學到的常常就是 TF 結合 motif 或其他位點特徵（如 splice site）。' },
  { course:'ml', q:'蛋白質語言模型「ESMFold」的主要訴求是？',
    opts:[
      '比 AlphaFold 更準',
      '不需要 MSA，純由序列預測結構',
      '預測 RNA 結構',
      '預測 protein-protein 交互作用',
    ],
    correct:1,
    note:'ESMFold 從預訓練語言模型抽 embedding 直接預測結構，免去 MSA 搜尋步驟，比 AlphaFold 快 60×。對孤兒蛋白（無同源）特別有價值。' },

  { course:'intro', q:'下列何者「不是」常見的生物資訊資料庫？',
    opts:['NCBI GenBank', 'Ensembl', 'PDB', 'GitHub'],
    correct:3,
    note:'GitHub 是程式碼託管平台，雖然很多生資工具放在上面，但不是「生資資料庫」本身。前三者是序列 / 基因組 / 結構資料庫。' },

  // ── 新章節題目 ──
  { course:'epi', q:'下列哪一個是「啟動子活化」的標準組蛋白標記？',
    opts:['H3K4me3', 'H3K27me3', 'H3K9me3', 'H4K20me1'],
    correct:0,
    note:'H3K4me3 標記活躍啟動子；H3K27me3 和 H3K9me3 反而是基因沉默 / 異染色質的標記。' },
  { course:'epi', q:'Bisulfite sequencing 的化學原理是？',
    opts:[
      '把甲基化 C 轉成 T',
      '把未甲基化 C 轉成 U (再變 T)',
      '直接讀出 5mC',
      '酵素切甲基化位點',
    ],
    correct:1,
    note:'Bisulfite 把未甲基化 C 去胺成 U（PCR 後變 T），保留甲基化 5mC。比對前後序列即可得位點甲基化狀態。' },
  { course:'epi', q:'ATAC-seq 比 ChIP-seq 的主要優勢是？',
    opts:['更精準', '不需抗體 + 樣本量少 + 一步完成', '解析度更高', '能定量蛋白量'],
    correct:1,
    note:'ATAC-seq 用 Tn5 直接切染色質開放區並插入定序 adapter，免去抗體與多步驟，特別適合稀少樣本與單細胞。' },

  { course:'cancer', q:'下列何者「不是」driver mutation 的特性？',
    opts:[
      '給細胞生長 / 存活優勢',
      '常落在 oncogene 或 TSG',
      '在腫瘤中突變率顯著高於背景',
      '對細胞表型無影響',
    ],
    correct:3,
    note:'Driver 的定義就是有功能影響、推動癌化。「無影響」是 passenger。' },
  { course:'cancer', q:'MSI-high 腫瘤的臨床意義是？',
    opts:[
      '對化療敏感',
      '對 PD-1 免疫治療反應率高',
      '預後極差',
      '完全無法治療',
    ],
    correct:1,
    note:'MSI-high 帶高突變負荷 → 新抗原多 → 免疫系統可辨識 → 對 PD-1 抑制劑反應好。FDA 第一個跨癌種的免疫治療生物標記。' },
  { course:'cancer', q:'SBS4 突變簽名最常對應的環境因子是？',
    opts:['紫外線', '抽菸', '酒精', '化療藥'],
    correct:1,
    note:'SBS4 是抽菸導致的特徵簽名 (C>A 在 NCC trinucleotide context)；SBS7 才是 UV。' },

  { course:'microbe', q:'16S rRNA 定序的最大限制是？',
    opts:[
      '無法看真核生物',
      '解析度通常只到屬級、無法看功能',
      '需要極大樣本量',
      '無法用於環境樣本',
    ],
    correct:1,
    note:'16S 只看單一基因，解析度通常停在屬 (genus) 級，且看不到代謝功能。要看功能要用 shotgun metagenomics 或 PICRUSt 推測。' },
  { course:'microbe', q:'ASV 比 OTU 的主要優勢是？',
    opts:[
      '更快',
      '單鹼基解析度且跨研究可合併',
      '更省記憶體',
      '不需 reference',
    ],
    correct:1,
    note:'OTU 用 97% 相似聚類，跨研究不可合併。DADA2 / Deblur 給出的 ASV 是去除錯誤後的真實 1 bp 解析度，跨資料集可直接合併。' },
  { course:'microbe', q:'β 多樣性常用的距離指標是？',
    opts:['Shannon index', 'Simpson index', 'Bray-Curtis / UniFrac', 'pLDDT'],
    correct:2,
    note:'Bray-Curtis 看組成差異；UniFrac 加入系統發生資訊。Shannon / Simpson 是 α 多樣性指標。' },

  { course:'crispr', q:'CRISPR-Cas9 切 DNA 需要什麼條件？',
    opts:[
      '只要 gRNA 配對',
      'gRNA 配對 + 旁邊有 PAM',
      '兩條 gRNA',
      'PCR 引子',
    ],
    correct:1,
    note:'SpCas9 需要 gRNA (20 nt) 配對目標 DNA + 緊鄰一個 NGG PAM (Protospacer Adjacent Motif)。缺一不可。' },
  { course:'crispr', q:'Base editor 相對於傳統 Cas9 的優勢是？',
    opts:[
      '不需要 gRNA',
      '不產生雙股斷裂 → 降低脫靶與 indel 風險',
      '能切任意位點',
      '不需 PAM',
    ],
    correct:1,
    note:'Base editor 用 nickase Cas9 + 脫氨酶直接化學換鹼基，免去 DSB → 細胞修復不確定性大幅降低。' },
  { course:'crispr', q:'CRISPR screen 分析中最常用的工具是？',
    opts:['MAGeCK', 'GATK', 'DESeq2', 'STAR'],
    correct:0,
    note:'MAGeCK 是 CRISPR screen 分析的事實標準，給出每基因的 enrichment score 與 p value。' },

  { course:'sys', q:'下列哪一個是「網路 motif」？',
    opts:[
      'BLAST hit',
      'Feed-forward loop',
      'PCA 主成分',
      'ATAC peak',
    ],
    correct:1,
    note:'Feed-forward loop、negative feedback、autoregulation 是生物網路中重複出現的「motif」 — 與電路設計概念類似。' },
  { course:'sys', q:'GSEA 比 ORA (over-representation analysis) 的主要優勢是？',
    opts:[
      '更快',
      '能抓「整條通路 mild but consistent 偏移」訊號',
      '不需要 gene set 資料庫',
      '完全自動',
    ],
    correct:1,
    note:'ORA 只看 top significant 基因；GSEA 看整個排名分布，因此能偵測 mild 但 systematic 的通路偏移。' },
  { course:'sys', q:'下列何者是 PPI 網路的高 degree (連線數) 蛋白 hub 的特性？',
    opts:[
      '通常無功能',
      '通常是必需 / essential 基因',
      '只有酵素才會是 hub',
      '不會出現在 STRING 資料庫',
    ],
    correct:1,
    note:'統計上 hub 蛋白與「必需基因」高度重疊 — 因為它們參與多種交互作用，敲掉影響大。' },

  { course:'cloud', q:'下列哪一個「不是」工作流系統的核心功能？',
    opts:[
      '失敗時從中斷處續跑',
      '自動平行排程',
      '版本控制 git 替代',
      '紀錄參數與環境',
    ],
    correct:2,
    note:'工作流系統與 git 並用 — 它「不是」要取代 git。其他三項都是工作流系統的核心功能。' },
  { course:'cloud', q:'Docker 與 Singularity 的主要差別是？',
    opts:[
      'Docker 較新',
      'Singularity 為 HPC 安全環境設計（不需 root）',
      'Singularity 不支援 Linux',
      'Docker 不能跑生資工具',
    ],
    correct:1,
    note:'Singularity / Apptainer 是 HPC（高效能叢集）容器標準，不需 root 權限，可跟 Slurm 整合。Docker image 可轉成 Singularity 用。' },
  { course:'cloud', q:'下列何者「不是」FAIR 原則的 F、A、I、R？',
    opts:['Findable', 'Accessible', 'Interoperable', 'Fast'],
    correct:3,
    note:'FAIR = Findable / Accessible / Interoperable / Reusable。「Fast」不在其中（速度不是可重現性的核心）。' },
];

Object.assign(window, { QUIZ_BANK });
